### ISSUE TITLE
The azure executor should use a fixed tag instead of latest 

### ISSUE THREAD

**Issue by maurelio1234** [CircleCI-Public/azure-cli-orb#13]
### Orb version

1.1.0

### What happened

This morning we have CircleCI failing because it cannot download the `latest` tag of the executor on some private jobs of us

![圖片](https://user-images.githubusercontent.com/6065520/122176321-c28da600-ce84-11eb-8acb-a69609cb5ba6.png)

For now we repaced your executor by the specific tag for the latest version of the image and it works

![圖片](https://user-images.githubusercontent.com/6065520/122176658-26b06a00-ce85-11eb-8db1-d110fd599047.png)

### Expected behavior

I'm not really sure if this `issue` is a bug or an enhancement, first of all it shouldn't fail on CircleCI, but then, the orb may stop working (like it did for us) when the reference image changes, since it's a moving target.

**Comment by lokst** [comment]
@maurelio1234 Thank you for filing this issue. Can you try using version `1.2.0`? We have just updated the orb to use a different image name: https://github.com/CircleCI-Public/azure-cli-orb/pull/11

**Comment by maurelio1234** [comment]
Oh, thank you very much  for your prompt response :) 
Yes, it works on v1.2.

**Comment by EricRibeiro** [comment]
The author commented that the orb version 1.2 fixes the issue, so I'll be closing this issue.
