### ISSUE TITLE
Should provide a parameter to specify subscription id

### ISSUE THREAD

**Issue by bingosummer** [CircleCI-Public/azure-cli-orb#3]
### Orb version

1.1.0

### What happened

After login, wrong subscription is used.

### Expected behavior

After login, azure-cli-orb should use `az account set -s <SUBSCRIPTION-ID>` to switch to the correct subscription. Because a service principal may be bound to multiple subscriptions, but users only want to create resources on one of the subscriptions. So the orb should provide a parameter to specify subscription id.

**Comment by iynere** [comment]
@bingosummer can you drop a link to a job where you saw this happen ? thank you !

**Comment by dsayling** [comment]
closing stale issue - please comment to reopen
